language: dart
dart:
  - dev
  - stable

install: ./tool/travis-setup.sh

jobs:
  include:
    - stage: test
      script: ./tool/travis.sh
      env: PUB_HOSTED_URL=https://pub.flutter-io.cn
    - stage: test
      script: ./tool/travis.sh

branches:
  only:
    - master
