name: pubcache
version: 0.0.1
description: A library to reflect on the local pub cache.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/pubcache

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  path: any
  pub_semver: any
  yaml: any

dev_dependencies:
  unittest: any
