name: pubcache
version: 0.0.1
description: A library to reflect on the local pub cache.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/pubcache

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any
dev_dependencies:
  unittest: any
