name: pub_cache
version: 0.0.1+2
description: A library to reflect on the local pub cache.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/pub_cache

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  path: '^1.0.0'
  pub_semver: '^1.0.0'
  yaml: '^2.0.0'

dev_dependencies:
  unittest: any
